### ISSUE TITLE
Crash upon selecting Ultilities button in settings

### ISSUE THREAD

**Issue by JayHuminaWuh** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#15]
When trying to enter the "utilities" subsection in the settings, the moment the button was pressed I received an error:

[string"?"]:597: bad argument #2 to 'format' (number expected, got nil)

upon pressing X to restart, I got another error:

[string "?"]:23: Network is already inited (sic)

**Comment by BlackSheepBoy69** [comment]
Ah! That's bad. I'll look into it!

**Comment by BlackSheepBoy69** [comment]
Is this your first time using the app? Have you ever changed the view style or any other settings or did you go straight to Utilities? Seems the issue is possibly related to a setting not properly formatting correctly when saved (The settings menu saves all current settings every time you press 'X' )

Try changing toggling any other setting, then try hitting 'Utilities'.... and if that doesn't work try changing language a few times until it goes back to the language you were using. Let me know if either of these work. I have an idea of how to fix the issue no matter what, but the more details (ex: telling me if changing ANY setting a few times works, and if not... THEN checking if changing language a few times makes you able to access 'Utilities') then with the more details I'll be able to fix it cleaner.

**Comment by BlackSheepBoy69** [comment]
Also instead of testing all these, just sending me this file will work just as well:

ux0:/data/HexFlow/config.dat

**Comment by Ranger-official** [comment]
I can confirm that I have the same issues, and that changing the language and 'Shadows & Reflections: ON...' results in the same crash. Would you like me to send you a config file as well?

**Comment by BlackSheepBoy69** [comment]
@Ranger-official
It would help for sure if you could send the file somehow. Thank you in advance if you can!

**Comment by Ranger-official** [comment]
The setting that crashed for me the RetroFlow is "Startup Categories" but only at a certain system but I don't know which one, also "Homebrews Category", so maybe it's a crash in there? 

ux0:/data/HexFlow/config.dat 11101000

**Comment by BlackSheepBoy69** [comment]
Thank you, that helped a lot. If the issue was with the old vs new format for 'setLanguage', then this version should fix your issue completely. Please let me know if you get any formatting errors or any issues relating to changing the setting "Start Category" in this new version please.

Also should fix Utility Menu not openning.

https://github.com/jimbob4000/RetroFlow-Launcher/releases/

**Comment by BlackSheepBoy69** [comment]
Any luck?

**Comment by Ranger-official** [comment]
Fixed my crashes! Just doesn't show my Retroflow games like N64 when toggled on.

**Comment by BlackSheepBoy69** [comment]
Gonna close as complete for now, as for your RetroFlow folders not showing up,

1: Are you using the latest version of RetroFlow?

2: Are your N64's in the default folders for the latest version of RetroFlow? ux0:data/RetroFlow/ROMS/Nintendo - Nintendo 64/

Also glad we got it not crashing, that's a good first step
