### ISSUE TITLE
In settings menu, no option to download homebrew covers

### ISSUE THREAD

**Issue by Invictaz** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#2]
There is only the setting download covers for psx/psp/psvita but not for homebrews (if they have covers).

**Comment by BlackSheepBoy69** [comment]
They do have covers, for example Bad Company 2 Android Port, Tomb Raider Classic Android Port, and Mario Kart Vita. They're vita style covers. Originally in v1.0.0 there was intended to be an option for it to override all at once every homebrew that had a cover, override it into vita and download said cover. It still has not been added yet but I'll definitely add it to the public "to-do list" since I had forgot to.

There will probably not be an option to download all homebrew covers without the app overriding them to vita for you all homebrew covers are vita-style due to a complication in HEXFlow launcher v0.5 where vita and homebrew share a cover folder and the community has been making vita-style homebrew covers ever since.

**Comment by BlackSheepBoy69** [comment]
Massively revamped the mass-cover-downloader in the new RetroFlow+Grid View update V2.0, there is now the option to download all "Vita"-style covers available for your homebrews en-masse.
