### ISSUE TITLE
Last played game feature 

### ISSUE THREAD

**Issue by fwannmacher** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#3]
A nice feature to add would be loading the app with the last played game highlighted. This way it is not necessary to search for the game everytime the console is turned on.

**Comment by fwannmacher** [comment]
I ended up doing it myself :-p
https://github.com/BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom/pull/4

**Comment by BlackSheepBoy69** [comment]
I'll be sure to add your pull #4 in the next version it sounds epic!!! Probably in a few weeks, HexLauncher Custom team is working with Retroflow team temporarily until their pre-release v4.0.1 becomes a stable (v4.1?).

**Comment by BlackSheepBoy69** [comment]
I posted an intermediary release while I'm still working out an annoying GPU crash for the RetroFlow integration and the lag caused by grid view before either of those 2 features get released. It's just that someone requested what's stable to be released.

Since the only issue with Last Played Game was that it collides with the RetroFlow, I added your pull check it out!

**Comment by BlackSheepBoy69** [comment]
Some people had issues with V1.1, this new version V1.2 should fix any issues if you had any while I go work out RetroFlow integration. Also it has a whole recently played category so that's pretty cool!

**Comment by fwannmacher** [comment]
I'm not doing it for any credit. I just wanted to help ;-)
